ALTER TABLE "driver_document_scans" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "scan_actor_read" ON "driver_document_scans" AS PERMISSIVE FOR SELECT TO public USING (NULLIF(current_setting('rove.actor_id',true),'') IS NOT NULL AND EXISTS(SELECT 1 FROM public.driver_documents d WHERE d.id="driver_document_scans"."document_id"));--> statement-breakpoint
CREATE POLICY "scan_owner_queue" ON "driver_document_scans" AS PERMISSIVE FOR INSERT TO public WITH CHECK (current_setting('rove.actor_role',true)='driver' AND EXISTS(SELECT 1 FROM public.driver_documents d WHERE d.id="driver_document_scans"."document_id" AND d.driver_id=NULLIF(current_setting('rove.actor_id',true),'')::uuid AND d.state='quarantined') AND "driver_document_scans"."state"='pending' AND "driver_document_scans"."attempts"=0 AND "driver_document_scans"."lease_token" IS NULL AND "driver_document_scans"."locked_until" IS NULL AND "driver_document_scans"."scanned_key" IS NULL AND "driver_document_scans"."scanned_version" IS NULL AND "driver_document_scans"."scanned_sha256" IS NULL AND "driver_document_scans"."completed_at" IS NULL);--> statement-breakpoint
CREATE POLICY "scan_staff_lock" ON "driver_document_scans" AS PERMISSIVE FOR UPDATE TO public USING (current_setting('rove.actor_role', true) = 'staff'
  AND current_setting('rove.actor_mfa', true) = 'true'
  AND EXISTS (SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id
    WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='staff' AND u.disabled=false AND p.permission='driver.document.review') OR current_setting('rove.actor_role', true) = 'staff'
  AND current_setting('rove.actor_mfa', true) = 'true'
  AND EXISTS (SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id
    WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='staff' AND u.disabled=false AND p.permission='driver.eligibility.review') OR current_setting('rove.actor_role', true) = 'staff'
  AND current_setting('rove.actor_mfa', true) = 'true'
  AND EXISTS (SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id
    WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='staff' AND u.disabled=false AND p.permission='privacy.read') OR current_setting('rove.actor_role', true) = 'staff'
  AND current_setting('rove.actor_mfa', true) = 'true'
  AND EXISTS (SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id
    WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='staff' AND u.disabled=false AND p.permission='privacy.cleanup')) WITH CHECK (false);--> statement-breakpoint
CREATE POLICY "scan_worker_read" ON "driver_document_scans" AS PERMISSIVE FOR SELECT TO public USING (NULLIF(current_setting('rove.actor_id',true),'') IS NULL AND (current_setting('rove.scan_queue',true)='true' OR "driver_document_scans"."document_id"=NULLIF(current_setting('rove.scan_document',true),'')::uuid) AND EXISTS(SELECT 1 FROM public.driver_documents d WHERE d.id="driver_document_scans"."document_id" AND d.state='quarantined'));--> statement-breakpoint
CREATE POLICY "scan_worker_claim" ON "driver_document_scans" AS PERMISSIVE FOR UPDATE TO public USING (NULLIF(current_setting('rove.actor_id',true),'') IS NULL AND current_setting('rove.scan_queue',true)='true' AND "driver_document_scans"."state"='pending' AND EXISTS(SELECT 1 FROM public.driver_documents d WHERE d.id="driver_document_scans"."document_id" AND d.state='quarantined')) WITH CHECK (NULLIF(current_setting('rove.actor_id',true),'') IS NULL AND current_setting('rove.scan_queue',true)='true' AND "driver_document_scans"."state"='pending');--> statement-breakpoint
CREATE POLICY "scan_worker_result" ON "driver_document_scans" AS PERMISSIVE FOR UPDATE TO public USING (NULLIF(current_setting('rove.actor_id',true),'') IS NULL AND "driver_document_scans"."document_id"=NULLIF(current_setting('rove.scan_document',true),'')::uuid AND EXISTS(SELECT 1 FROM public.driver_documents d WHERE d.id="driver_document_scans"."document_id" AND d.state='quarantined')) WITH CHECK (NULLIF(current_setting('rove.actor_id',true),'') IS NULL AND "driver_document_scans"."document_id"=NULLIF(current_setting('rove.scan_document',true),'')::uuid);
--> statement-breakpoint
ALTER TABLE "driver_document_scans" FORCE ROW LEVEL SECURITY;
