ALTER TABLE "document_storage_writes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "storage_write_actor_read" ON "document_storage_writes" AS PERMISSIVE FOR SELECT TO public USING ((current_setting('rove.actor_role',true)='driver' OR current_setting('rove.actor_role', true) = 'staff'
  AND current_setting('rove.actor_mfa', true) = 'true'
  AND EXISTS (SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id
    WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='staff' AND u.disabled=false AND p.permission='privacy.read') OR current_setting('rove.actor_role', true) = 'staff'
  AND current_setting('rove.actor_mfa', true) = 'true'
  AND EXISTS (SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id
    WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='staff' AND u.disabled=false AND p.permission='privacy.cleanup')) AND EXISTS(SELECT 1 FROM public.driver_documents d WHERE d.id="document_storage_writes"."document_id"));--> statement-breakpoint
CREATE POLICY "storage_write_owner_insert" ON "document_storage_writes" AS PERMISSIVE FOR INSERT TO public WITH CHECK (current_setting('rove.actor_role',true)='driver' AND EXISTS(SELECT 1 FROM public.driver_documents d WHERE d.id="document_storage_writes"."document_id" AND d.driver_id=NULLIF(current_setting('rove.actor_id',true),'')::uuid AND d.state='reserved' AND d.expires_at>clock_timestamp()) AND "document_storage_writes"."settled_at" IS NULL AND "document_storage_writes"."not_dispatched_at" IS NULL AND "document_storage_writes"."object_version" IS NULL);--> statement-breakpoint
CREATE POLICY "storage_write_cleanup_read" ON "document_storage_writes" AS PERMISSIVE FOR SELECT TO public USING (NULLIF(current_setting('rove.actor_id',true),'') IS NULL AND NULLIF(current_setting('rove.cleanup_item',true),'') IS NOT NULL AND EXISTS(SELECT 1 FROM public.driver_documents d WHERE d.id="document_storage_writes"."document_id"));--> statement-breakpoint
CREATE POLICY "storage_write_receipt_read" ON "document_storage_writes" AS PERMISSIVE FOR SELECT TO public USING (NULLIF(current_setting('rove.actor_id',true),'') IS NULL AND "document_storage_writes"."document_id"=NULLIF(current_setting('rove.write_document',true),'')::uuid AND "document_storage_writes"."object_key"=current_setting('rove.write_key',true));--> statement-breakpoint
CREATE POLICY "storage_write_receipt_update" ON "document_storage_writes" AS PERMISSIVE FOR UPDATE TO public USING (NULLIF(current_setting('rove.actor_id',true),'') IS NULL AND "document_storage_writes"."document_id"=NULLIF(current_setting('rove.write_document',true),'')::uuid AND "document_storage_writes"."object_key"=current_setting('rove.write_key',true)) WITH CHECK (NULLIF(current_setting('rove.actor_id',true),'') IS NULL AND "document_storage_writes"."document_id"=NULLIF(current_setting('rove.write_document',true),'')::uuid AND "document_storage_writes"."object_key"=current_setting('rove.write_key',true));
--> statement-breakpoint
ALTER TABLE "document_storage_writes" FORCE ROW LEVEL SECURITY;
