ALTER TABLE "push_deliveries" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "push_delivery_recipient_read" ON "push_deliveries" AS PERMISSIVE FOR SELECT TO public USING ("push_deliveries"."event_id"=NULLIF(current_setting('rove.push_event',true),'')::uuid AND "push_deliveries"."installation_id"=NULLIF(current_setting('rove.push_installation',true),'')::uuid AND "push_deliveries"."revision"=NULLIF(current_setting('rove.push_revision',true),'')::int);--> statement-breakpoint
CREATE POLICY "push_delivery_recipient_insert" ON "push_deliveries" AS PERMISSIVE FOR INSERT TO public WITH CHECK ("push_deliveries"."event_id"=NULLIF(current_setting('rove.push_event',true),'')::uuid AND "push_deliveries"."installation_id"=NULLIF(current_setting('rove.push_installation',true),'')::uuid AND "push_deliveries"."revision"=NULLIF(current_setting('rove.push_revision',true),'')::int AND "push_deliveries"."state"='pending' AND "push_deliveries"."attempts"=0 AND "push_deliveries"."receipt_attempts"=0 AND "push_deliveries"."receipt_id" IS NULL AND "push_deliveries"."accepted_at" IS NULL AND "push_deliveries"."lease_token" IS NULL AND "push_deliveries"."locked_until" IS NULL AND "push_deliveries"."last_error" IS NULL);--> statement-breakpoint
CREATE POLICY "push_delivery_worker_read" ON "push_deliveries" AS PERMISSIVE FOR SELECT TO public USING ("push_deliveries"."id"=NULLIF(current_setting('rove.push_delivery',true),'')::uuid);--> statement-breakpoint
CREATE POLICY "push_delivery_worker_update" ON "push_deliveries" AS PERMISSIVE FOR UPDATE TO public USING ("push_deliveries"."id"=NULLIF(current_setting('rove.push_delivery',true),'')::uuid) WITH CHECK ("push_deliveries"."id"=NULLIF(current_setting('rove.push_delivery',true),'')::uuid);--> statement-breakpoint
CREATE POLICY "push_delivery_recovery_read" ON "push_deliveries" AS PERMISSIVE FOR SELECT TO public USING ("push_deliveries"."state" IN ('pending','sending','receipt') AND "push_deliveries"."updated_at"<NULLIF(current_setting('rove.push_recovery_at',true),'')::timestamptz-interval '20 minutes' AND ("push_deliveries"."locked_until" IS NULL OR "push_deliveries"."locked_until"<=NULLIF(current_setting('rove.push_recovery_at',true),'')::timestamptz));--> statement-breakpoint
CREATE POLICY "push_delivery_recovery_lock" ON "push_deliveries" AS PERMISSIVE FOR UPDATE TO public USING ("push_deliveries"."state" IN ('pending','sending','receipt') AND "push_deliveries"."updated_at"<NULLIF(current_setting('rove.push_recovery_at',true),'')::timestamptz-interval '20 minutes' AND ("push_deliveries"."locked_until" IS NULL OR "push_deliveries"."locked_until"<=NULLIF(current_setting('rove.push_recovery_at',true),'')::timestamptz)) WITH CHECK (false);
--> statement-breakpoint
ALTER TABLE "push_deliveries" FORCE ROW LEVEL SECURITY;
