ALTER TABLE "push_installations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "installation_owner_read" ON "push_installations" AS PERMISSIVE FOR SELECT TO public USING ("push_installations"."owner_id"=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND current_setting('rove.actor_role',true) IN ('rider','driver')
  AND EXISTS(SELECT 1 FROM public.users u WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role=current_setting('rove.actor_role',true) AND u.disabled=false));--> statement-breakpoint
CREATE POLICY "installation_owner_insert" ON "push_installations" AS PERMISSIVE FOR INSERT TO public WITH CHECK ("push_installations"."owner_id"=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND current_setting('rove.actor_role',true) IN ('rider','driver')
  AND EXISTS(SELECT 1 FROM public.users u WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role=current_setting('rove.actor_role',true) AND u.disabled=false) AND "push_installations"."project_id"=NULLIF(current_setting('rove.install_project',true),'')::uuid AND "push_installations"."installation_id"=NULLIF(current_setting('rove.install_lookup',true),'')::uuid);--> statement-breakpoint
CREATE POLICY "installation_owner_update" ON "push_installations" AS PERMISSIVE FOR UPDATE TO public USING ("push_installations"."owner_id"=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND current_setting('rove.actor_role',true) IN ('rider','driver')
  AND EXISTS(SELECT 1 FROM public.users u WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role=current_setting('rove.actor_role',true) AND u.disabled=false)) WITH CHECK ("push_installations"."owner_id"=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND current_setting('rove.actor_role',true) IN ('rider','driver')
  AND EXISTS(SELECT 1 FROM public.users u WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role=current_setting('rove.actor_role',true) AND u.disabled=false));--> statement-breakpoint
CREATE POLICY "installation_lookup_read" ON "push_installations" AS PERMISSIVE FOR SELECT TO public USING (NULLIF(current_setting('rove.actor_id', true), '')::uuid=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND current_setting('rove.actor_role',true) IN ('rider','driver')
  AND EXISTS(SELECT 1 FROM public.users u WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role=current_setting('rove.actor_role',true) AND u.disabled=false) AND "push_installations"."project_id"=NULLIF(current_setting('rove.install_project',true),'')::uuid AND ("push_installations"."installation_id"=NULLIF(current_setting('rove.install_lookup',true),'')::uuid OR "push_installations"."token"=NULLIF(current_setting('rove.install_token',true),'')));--> statement-breakpoint
CREATE POLICY "installation_transfer" ON "push_installations" AS PERMISSIVE FOR UPDATE TO public USING (NULLIF(current_setting('rove.actor_id', true), '')::uuid=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND current_setting('rove.actor_role',true) IN ('rider','driver')
  AND EXISTS(SELECT 1 FROM public.users u WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role=current_setting('rove.actor_role',true) AND u.disabled=false) AND "push_installations"."project_id"=NULLIF(current_setting('rove.install_project',true),'')::uuid AND "push_installations"."installation_id"=NULLIF(current_setting('rove.install_lookup',true),'')::uuid) WITH CHECK ("push_installations"."owner_id"=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND current_setting('rove.actor_role',true) IN ('rider','driver')
  AND EXISTS(SELECT 1 FROM public.users u WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role=current_setting('rove.actor_role',true) AND u.disabled=false));--> statement-breakpoint
CREATE POLICY "installation_staff_read" ON "push_installations" AS PERMISSIVE FOR SELECT TO public USING (current_setting('rove.actor_role', true) = 'staff'
  AND current_setting('rove.actor_mfa', true) = 'true'
  AND EXISTS (SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id
    WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='staff' AND u.disabled=false AND p.permission='privacy.read') OR current_setting('rove.actor_role', true) = 'staff'
  AND current_setting('rove.actor_mfa', true) = 'true'
  AND EXISTS (SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id
    WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='staff' AND u.disabled=false AND p.permission='privacy.close'));--> statement-breakpoint
CREATE POLICY "installation_close" ON "push_installations" AS PERMISSIVE FOR UPDATE TO public USING (current_setting('rove.actor_role', true) = 'staff'
  AND current_setting('rove.actor_mfa', true) = 'true'
  AND EXISTS (SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id
    WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='staff' AND u.disabled=false AND p.permission='privacy.close') AND EXISTS(SELECT 1 FROM public.users u WHERE u.id="push_installations"."owner_id" AND u.disabled=true)) WITH CHECK (current_setting('rove.actor_role', true) = 'staff'
  AND current_setting('rove.actor_mfa', true) = 'true'
  AND EXISTS (SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id
    WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='staff' AND u.disabled=false AND p.permission='privacy.close') AND "push_installations"."enabled"=false AND "push_installations"."token"='' AND EXISTS(SELECT 1 FROM public.users u WHERE u.id="push_installations"."owner_id" AND u.disabled=true));--> statement-breakpoint
CREATE POLICY "installation_audience_read" ON "push_installations" AS PERMISSIVE FOR SELECT TO public USING (("push_installations"."owner_id"=NULLIF(current_setting('rove.audience_rider',true),'')::uuid AND "push_installations"."project_id"=NULLIF(current_setting('rove.audience_rider_project',true),'')::uuid) OR ("push_installations"."owner_id"=NULLIF(current_setting('rove.audience_driver',true),'')::uuid AND "push_installations"."project_id"=NULLIF(current_setting('rove.audience_driver_project',true),'')::uuid));--> statement-breakpoint
CREATE POLICY "installation_worker_read" ON "push_installations" AS PERMISSIVE FOR SELECT TO public USING ("push_installations"."id"=NULLIF(current_setting('rove.install_target',true),'')::uuid);--> statement-breakpoint
CREATE POLICY "installation_invalidate" ON "push_installations" AS PERMISSIVE FOR UPDATE TO public USING ("push_installations"."id"=NULLIF(current_setting('rove.install_target',true),'')::uuid AND "push_installations"."revision"=NULLIF(current_setting('rove.install_revision',true),'')::int) WITH CHECK ("push_installations"."id"=NULLIF(current_setting('rove.install_target',true),'')::uuid AND "push_installations"."revision"=NULLIF(current_setting('rove.install_revision',true),'')::int+1 AND "push_installations"."enabled"=false);
--> statement-breakpoint
ALTER TABLE "push_installations" FORCE ROW LEVEL SECURITY;
