ALTER TABLE "payment_refund_checks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "payment_refund_observations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "refund_check_read" ON "payment_refund_checks" AS PERMISSIVE FOR SELECT TO public USING (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="payment_refund_checks"."attempt_id" AND p.source=current_setting('rove.refund_source',true)) AND ("payment_refund_checks"."attempt_id"=NULLIF(current_setting('rove.refund_read',true),'')::uuid OR "payment_refund_checks"."attempt_id"=NULLIF(current_setting('rove.refund_write',true),'')::uuid) OR (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="payment_refund_checks"."attempt_id" AND p.source=current_setting('rove.refund_source',true)) AND current_setting('rove.refund_sweep',true)='true'));--> statement-breakpoint
CREATE POLICY "refund_check_insert" ON "payment_refund_checks" AS PERMISSIVE FOR INSERT TO public WITH CHECK (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="payment_refund_checks"."attempt_id" AND p.source=current_setting('rove.refund_source',true)) AND "payment_refund_checks"."attempt_id"=NULLIF(current_setting('rove.refund_write',true),'')::uuid);--> statement-breakpoint
CREATE POLICY "refund_check_update" ON "payment_refund_checks" AS PERMISSIVE FOR UPDATE TO public USING (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="payment_refund_checks"."attempt_id" AND p.source=current_setting('rove.refund_source',true)) AND "payment_refund_checks"."attempt_id"=NULLIF(current_setting('rove.refund_write',true),'')::uuid) WITH CHECK (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="payment_refund_checks"."attempt_id" AND p.source=current_setting('rove.refund_source',true)) AND "payment_refund_checks"."attempt_id"=NULLIF(current_setting('rove.refund_write',true),'')::uuid);--> statement-breakpoint
CREATE POLICY "refund_check_read_lock" ON "payment_refund_checks" AS PERMISSIVE FOR UPDATE TO public USING (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="payment_refund_checks"."attempt_id" AND p.source=current_setting('rove.refund_source',true)) AND ("payment_refund_checks"."attempt_id"=NULLIF(current_setting('rove.refund_read',true),'')::uuid OR "payment_refund_checks"."attempt_id"=NULLIF(current_setting('rove.refund_write',true),'')::uuid)) WITH CHECK (false);--> statement-breakpoint
CREATE POLICY "refund_observation_read" ON "payment_refund_observations" AS PERMISSIVE FOR SELECT TO public USING (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="payment_refund_observations"."attempt_id" AND p.source=current_setting('rove.refund_source',true)) AND ("payment_refund_observations"."attempt_id"=NULLIF(current_setting('rove.refund_read',true),'')::uuid OR "payment_refund_observations"."attempt_id"=NULLIF(current_setting('rove.refund_write',true),'')::uuid));--> statement-breakpoint
CREATE POLICY "refund_observation_insert" ON "payment_refund_observations" AS PERMISSIVE FOR INSERT TO public WITH CHECK (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="payment_refund_observations"."attempt_id" AND p.source=current_setting('rove.refund_source',true)) AND "payment_refund_observations"."attempt_id"=NULLIF(current_setting('rove.refund_write',true),'')::uuid);
--> statement-breakpoint
ALTER TABLE "payment_refund_checks" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "payment_refund_observations" FORCE ROW LEVEL SECURITY;
