ALTER TABLE "payment_dispute_checks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "payment_dispute_observations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "dispute_check_read" ON "payment_dispute_checks" AS PERMISSIVE FOR SELECT TO public USING (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="payment_dispute_checks"."attempt_id" AND p.source=current_setting('rove.dispute_source',true)) AND ("payment_dispute_checks"."attempt_id"=NULLIF(current_setting('rove.dispute_read',true),'')::uuid OR "payment_dispute_checks"."attempt_id"=NULLIF(current_setting('rove.dispute_write',true),'')::uuid) OR (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="payment_dispute_checks"."attempt_id" AND p.source=current_setting('rove.dispute_source',true)) AND (current_setting('rove.dispute_sweep',true)='true' OR current_setting('rove.actor_role', true) = 'staff'
  AND current_setting('rove.actor_mfa', true) = 'true'
  AND EXISTS (SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id
    WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='staff' AND u.disabled=false AND p.permission='payments.dispute.review'))));--> statement-breakpoint
CREATE POLICY "dispute_check_insert" ON "payment_dispute_checks" AS PERMISSIVE FOR INSERT TO public WITH CHECK (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="payment_dispute_checks"."attempt_id" AND p.source=current_setting('rove.dispute_source',true)) AND "payment_dispute_checks"."attempt_id"=NULLIF(current_setting('rove.dispute_write',true),'')::uuid);--> statement-breakpoint
CREATE POLICY "dispute_check_update" ON "payment_dispute_checks" AS PERMISSIVE FOR UPDATE TO public USING (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="payment_dispute_checks"."attempt_id" AND p.source=current_setting('rove.dispute_source',true)) AND "payment_dispute_checks"."attempt_id"=NULLIF(current_setting('rove.dispute_write',true),'')::uuid) WITH CHECK (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="payment_dispute_checks"."attempt_id" AND p.source=current_setting('rove.dispute_source',true)) AND "payment_dispute_checks"."attempt_id"=NULLIF(current_setting('rove.dispute_write',true),'')::uuid);--> statement-breakpoint
CREATE POLICY "dispute_check_read_lock" ON "payment_dispute_checks" AS PERMISSIVE FOR UPDATE TO public USING (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="payment_dispute_checks"."attempt_id" AND p.source=current_setting('rove.dispute_source',true)) AND ("payment_dispute_checks"."attempt_id"=NULLIF(current_setting('rove.dispute_read',true),'')::uuid OR "payment_dispute_checks"."attempt_id"=NULLIF(current_setting('rove.dispute_write',true),'')::uuid)) WITH CHECK (false);--> statement-breakpoint
CREATE POLICY "dispute_observation_read" ON "payment_dispute_observations" AS PERMISSIVE FOR SELECT TO public USING (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="payment_dispute_observations"."attempt_id" AND p.source=current_setting('rove.dispute_source',true)) AND ("payment_dispute_observations"."attempt_id"=NULLIF(current_setting('rove.dispute_read',true),'')::uuid OR "payment_dispute_observations"."attempt_id"=NULLIF(current_setting('rove.dispute_write',true),'')::uuid));--> statement-breakpoint
CREATE POLICY "dispute_observation_insert" ON "payment_dispute_observations" AS PERMISSIVE FOR INSERT TO public WITH CHECK (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="payment_dispute_observations"."attempt_id" AND p.source=current_setting('rove.dispute_source',true)) AND "payment_dispute_observations"."attempt_id"=NULLIF(current_setting('rove.dispute_write',true),'')::uuid);
--> statement-breakpoint
ALTER TABLE "payment_dispute_checks" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "payment_dispute_observations" FORCE ROW LEVEL SECURITY;
