ALTER TABLE "refund_operations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "refund_operation_read" ON "refund_operations" AS PERMISSIVE FOR SELECT TO public USING (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="refund_operations"."attempt_id" AND p.source=current_setting('rove.refund_operation_source',true)) AND ("refund_operations"."attempt_id"=NULLIF(current_setting('rove.refund_operation_attempt',true),'')::uuid OR "refund_operations"."id"=NULLIF(current_setting('rove.refund_operation_read',true),'')::uuid OR "refund_operations"."id"=NULLIF(current_setting('rove.refund_operation_write',true),'')::uuid));--> statement-breakpoint
CREATE POLICY "refund_operation_authorize" ON "refund_operations" AS PERMISSIVE FOR INSERT TO public WITH CHECK (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="refund_operations"."attempt_id" AND p.source=current_setting('rove.refund_operation_source',true)) AND "refund_operations"."attempt_id"=NULLIF(current_setting('rove.refund_operation_attempt',true),'')::uuid AND current_setting('rove.actor_role', true) = 'staff'
  AND current_setting('rove.actor_mfa', true) = 'true'
  AND EXISTS (SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id
    WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='staff' AND u.disabled=false AND p.permission='payments.refund') AND "refund_operations"."authorized_by"=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND "refund_operations"."state"='queued' AND "refund_operations"."provider_refund_id" IS NULL AND "refund_operations"."first_attempt_at" IS NULL);--> statement-breakpoint
CREATE POLICY "refund_operation_execute" ON "refund_operations" AS PERMISSIVE FOR UPDATE TO public USING (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="refund_operations"."attempt_id" AND p.source=current_setting('rove.refund_operation_source',true)) AND "refund_operations"."id"=NULLIF(current_setting('rove.refund_operation_write',true),'')::uuid) WITH CHECK (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="refund_operations"."attempt_id" AND p.source=current_setting('rove.refund_operation_source',true)) AND "refund_operations"."id"=NULLIF(current_setting('rove.refund_operation_write',true),'')::uuid);--> statement-breakpoint
CREATE POLICY "refund_operation_closure_read" ON "refund_operations" AS PERMISSIVE FOR SELECT TO public USING (current_setting('rove.actor_role', true) = 'staff'
  AND current_setting('rove.actor_mfa', true) = 'true'
  AND EXISTS (SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id
    WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='staff' AND u.disabled=false AND p.permission='privacy.close') AND EXISTS(SELECT 1 FROM public.payment_attempts p JOIN public.rides r ON r.id=p.ride_id WHERE p.id="refund_operations"."attempt_id" AND (r.rider_id=NULLIF(current_setting('rove.refund_closure_owner',true),'')::uuid OR r.driver_id=NULLIF(current_setting('rove.refund_closure_owner',true),'')::uuid)));
--> statement-breakpoint
ALTER TABLE "refund_operations" FORCE ROW LEVEL SECURITY;
