ALTER TABLE "driver_transfer_movements" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "driver_transfer_operations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "transfer_movement_read" ON "driver_transfer_movements" AS PERMISSIVE FOR SELECT TO public USING ("driver_transfer_movements"."source"=current_setting('rove.transfer_source',true) AND ("driver_transfer_movements"."operation_id"=NULLIF(current_setting('rove.transfer_read',true),'')::uuid OR "driver_transfer_movements"."operation_id"=NULLIF(current_setting('rove.transfer_write',true),'')::uuid OR "driver_transfer_movements"."balance_id"=NULLIF(current_setting('rove.transfer_balance',true),'')));--> statement-breakpoint
CREATE POLICY "transfer_movement_insert" ON "driver_transfer_movements" AS PERMISSIVE FOR INSERT TO public WITH CHECK ("driver_transfer_movements"."source"=current_setting('rove.transfer_source',true) AND "driver_transfer_movements"."operation_id"=NULLIF(current_setting('rove.transfer_write',true),'')::uuid);--> statement-breakpoint
CREATE POLICY "transfer_operation_read" ON "driver_transfer_operations" AS PERMISSIVE FOR SELECT TO public USING (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="driver_transfer_operations"."attempt_id" AND p.source=current_setting('rove.transfer_source',true)) AND ("driver_transfer_operations"."attempt_id"=NULLIF(current_setting('rove.transfer_attempt',true),'')::uuid OR "driver_transfer_operations"."id"=NULLIF(current_setting('rove.transfer_read',true),'')::uuid OR "driver_transfer_operations"."id"=NULLIF(current_setting('rove.transfer_write',true),'')::uuid OR current_setting('rove.transfer_sweep',true)='true'));--> statement-breakpoint
CREATE POLICY "transfer_operation_authorize" ON "driver_transfer_operations" AS PERMISSIVE FOR INSERT TO public WITH CHECK (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="driver_transfer_operations"."attempt_id" AND p.source=current_setting('rove.transfer_source',true)) AND "driver_transfer_operations"."attempt_id"=NULLIF(current_setting('rove.transfer_attempt',true),'')::uuid AND current_setting('rove.actor_role', true) = 'staff'
  AND current_setting('rove.actor_mfa', true) = 'true'
  AND EXISTS (SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id
    WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='staff' AND u.disabled=false AND p.permission='payments.transfer') AND "driver_transfer_operations"."authorized_by"=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND "driver_transfer_operations"."state"='queued' AND "driver_transfer_operations"."first_attempt_at" IS NULL AND "driver_transfer_operations"."charge_id" IS NULL AND "driver_transfer_operations"."provider_transfer_id" IS NULL AND "driver_transfer_operations"."revision"=0 AND "driver_transfer_operations"."reversed_cents"=0 AND "driver_transfer_operations"."checked_at" IS NULL AND "driver_transfer_operations"."requested_at" IS NULL);--> statement-breakpoint
CREATE POLICY "transfer_operation_update" ON "driver_transfer_operations" AS PERMISSIVE FOR UPDATE TO public USING (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="driver_transfer_operations"."attempt_id" AND p.source=current_setting('rove.transfer_source',true)) AND "driver_transfer_operations"."id"=NULLIF(current_setting('rove.transfer_write',true),'')::uuid) WITH CHECK (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="driver_transfer_operations"."attempt_id" AND p.source=current_setting('rove.transfer_source',true)) AND "driver_transfer_operations"."id"=NULLIF(current_setting('rove.transfer_write',true),'')::uuid);--> statement-breakpoint
CREATE POLICY "transfer_sweep_lock" ON "driver_transfer_operations" AS PERMISSIVE FOR UPDATE TO public USING (EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="driver_transfer_operations"."attempt_id" AND p.source=current_setting('rove.transfer_source',true)) AND current_setting('rove.transfer_sweep',true)='true') WITH CHECK (false);--> statement-breakpoint
CREATE POLICY "transfer_closure_read" ON "driver_transfer_operations" AS PERMISSIVE FOR SELECT TO public USING (current_setting('rove.actor_role', true) = 'staff'
  AND current_setting('rove.actor_mfa', true) = 'true'
  AND EXISTS (SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id
    WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='staff' AND u.disabled=false AND p.permission='privacy.close') AND "driver_transfer_operations"."driver_id"=NULLIF(current_setting('rove.transfer_closure_owner',true),'')::uuid);
--> statement-breakpoint
ALTER TABLE "driver_transfer_operations" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "driver_transfer_movements" FORCE ROW LEVEL SECURITY;
