ALTER TABLE "driver_payout_accounts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "payout_owner_read" ON "driver_payout_accounts" AS PERMISSIVE FOR SELECT TO public USING ("driver_payout_accounts"."source"=current_setting('rove.payout_source',true) AND "driver_payout_accounts"."driver_id"=NULLIF(current_setting('rove.actor_id',true),'')::uuid AND current_setting('rove.actor_role',true)='driver' AND EXISTS(SELECT 1 FROM public.users u WHERE u.id="driver_payout_accounts"."driver_id" AND u.role='driver' AND u.disabled=false));--> statement-breakpoint
CREATE POLICY "payout_owner_reserve" ON "driver_payout_accounts" AS PERMISSIVE FOR INSERT TO public WITH CHECK ("driver_payout_accounts"."source"=current_setting('rove.payout_source',true) AND "driver_payout_accounts"."driver_id"=NULLIF(current_setting('rove.actor_id',true),'')::uuid AND current_setting('rove.actor_role',true)='driver' AND EXISTS(SELECT 1 FROM public.users u WHERE u.id="driver_payout_accounts"."driver_id" AND u.role='driver' AND u.disabled=false) AND "driver_payout_accounts"."account_id" IS NULL AND "driver_payout_accounts"."sync_revision"=0 AND "driver_payout_accounts"."status"='unknown' AND "driver_payout_accounts"."checked_at" IS NULL AND "driver_payout_accounts"."last_requested_at" IS NULL);--> statement-breakpoint
CREATE POLICY "payout_worker_read" ON "driver_payout_accounts" AS PERMISSIVE FOR SELECT TO public USING ("driver_payout_accounts"."source"=current_setting('rove.payout_source',true) AND ("driver_payout_accounts"."driver_id"=NULLIF(current_setting('rove.payout_driver',true),'')::uuid OR "driver_payout_accounts"."account_id"=NULLIF(current_setting('rove.payout_account',true),'') OR "driver_payout_accounts"."id"=NULLIF(current_setting('rove.payout_binding',true),'')::uuid OR current_setting('rove.payout_sweep',true)='true'));--> statement-breakpoint
CREATE POLICY "payout_read_lock" ON "driver_payout_accounts" AS PERMISSIVE FOR UPDATE TO public USING ("driver_payout_accounts"."source"=current_setting('rove.payout_source',true) AND "driver_payout_accounts"."driver_id"=NULLIF(current_setting('rove.actor_id',true),'')::uuid AND current_setting('rove.actor_role',true)='driver' AND EXISTS(SELECT 1 FROM public.users u WHERE u.id="driver_payout_accounts"."driver_id" AND u.role='driver' AND u.disabled=false) OR "driver_payout_accounts"."source"=current_setting('rove.payout_source',true) AND ("driver_payout_accounts"."driver_id"=NULLIF(current_setting('rove.payout_driver',true),'')::uuid OR "driver_payout_accounts"."account_id"=NULLIF(current_setting('rove.payout_account',true),'') OR "driver_payout_accounts"."id"=NULLIF(current_setting('rove.payout_binding',true),'')::uuid OR current_setting('rove.payout_sweep',true)='true')) WITH CHECK (false);--> statement-breakpoint
CREATE POLICY "payout_worker_update" ON "driver_payout_accounts" AS PERMISSIVE FOR UPDATE TO public USING ("driver_payout_accounts"."source"=current_setting('rove.payout_source',true) AND ("driver_payout_accounts"."account_id"=NULLIF(current_setting('rove.payout_account',true),'') OR ("driver_payout_accounts"."id"=NULLIF(current_setting('rove.payout_binding',true),'')::uuid AND COALESCE(current_setting('rove.payout_result',true),'')=''))) WITH CHECK ("driver_payout_accounts"."source"=current_setting('rove.payout_source',true) AND ("driver_payout_accounts"."account_id"=NULLIF(current_setting('rove.payout_account',true),'') OR ("driver_payout_accounts"."id"=NULLIF(current_setting('rove.payout_binding',true),'')::uuid AND COALESCE(current_setting('rove.payout_result',true),'')='')));--> statement-breakpoint
CREATE POLICY "payout_result_update" ON "driver_payout_accounts" AS PERMISSIVE FOR UPDATE TO public USING ("driver_payout_accounts"."source"=current_setting('rove.payout_source',true) AND "driver_payout_accounts"."id"=NULLIF(current_setting('rove.payout_binding',true),'')::uuid AND COALESCE(current_setting('rove.payout_result',true),'')<>'' AND ("driver_payout_accounts"."account_id" IS NULL OR "driver_payout_accounts"."account_id"=current_setting('rove.payout_result',true))) WITH CHECK ("driver_payout_accounts"."source"=current_setting('rove.payout_source',true) AND "driver_payout_accounts"."id"=NULLIF(current_setting('rove.payout_binding',true),'')::uuid AND COALESCE(current_setting('rove.payout_result',true),'')<>'' AND "driver_payout_accounts"."account_id"=current_setting('rove.payout_result',true));
--> statement-breakpoint
ALTER TABLE "driver_payout_accounts" FORCE ROW LEVEL SECURITY;
