ALTER TABLE "driver_tracking_sessions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "tracking_read" ON "driver_tracking_sessions" AS PERMISSIVE FOR SELECT TO public USING ("driver_tracking_sessions"."driver_id"=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND current_setting('rove.actor_role',true)='driver'
  AND EXISTS(SELECT 1 FROM public.users u WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='driver' AND u.disabled=false) OR "driver_tracking_sessions"."token_hash"=NULLIF(current_setting('rove.tracking_hash',true),'') OR current_setting('rove.actor_role', true) = 'staff'
  AND current_setting('rove.actor_mfa', true) = 'true'
  AND EXISTS (SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id
    WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='staff' AND u.disabled=false AND p.permission='privacy.close') AND "driver_tracking_sessions"."driver_id"=NULLIF(current_setting('rove.tracking_close_owner',true),'')::uuid AND EXISTS(SELECT 1 FROM public.users u WHERE u.id="driver_tracking_sessions"."driver_id" AND u.disabled=true));--> statement-breakpoint
CREATE POLICY "tracking_issue_insert" ON "driver_tracking_sessions" AS PERMISSIVE FOR INSERT TO public WITH CHECK ("driver_tracking_sessions"."driver_id"=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND current_setting('rove.actor_role',true)='driver'
  AND EXISTS(SELECT 1 FROM public.users u WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='driver' AND u.disabled=false) AND current_setting('rove.tracking_mode',true)='issue' AND "driver_tracking_sessions"."token_hash"=NULLIF(current_setting('rove.tracking_hash',true),'') AND EXISTS(SELECT 1 FROM public.drivers d WHERE d.id="driver_tracking_sessions"."driver_id" AND d.online));--> statement-breakpoint
CREATE POLICY "tracking_issue_update" ON "driver_tracking_sessions" AS PERMISSIVE FOR UPDATE TO public USING ("driver_tracking_sessions"."driver_id"=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND current_setting('rove.actor_role',true)='driver'
  AND EXISTS(SELECT 1 FROM public.users u WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='driver' AND u.disabled=false) AND current_setting('rove.tracking_mode',true)='issue') WITH CHECK ("driver_tracking_sessions"."driver_id"=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND current_setting('rove.actor_role',true)='driver'
  AND EXISTS(SELECT 1 FROM public.users u WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='driver' AND u.disabled=false) AND current_setting('rove.tracking_mode',true)='issue' AND "driver_tracking_sessions"."token_hash"=NULLIF(current_setting('rove.tracking_hash',true),'') AND EXISTS(SELECT 1 FROM public.drivers d WHERE d.id="driver_tracking_sessions"."driver_id" AND d.online));--> statement-breakpoint
CREATE POLICY "tracking_read_lock" ON "driver_tracking_sessions" AS PERMISSIVE FOR UPDATE TO public USING ("driver_tracking_sessions"."token_hash"=NULLIF(current_setting('rove.tracking_hash',true),'')) WITH CHECK (false);--> statement-breakpoint
CREATE POLICY "tracking_sample" ON "driver_tracking_sessions" AS PERMISSIVE FOR UPDATE TO public USING ("driver_tracking_sessions"."token_hash"=NULLIF(current_setting('rove.tracking_hash',true),'') AND current_setting('rove.tracking_mode',true)='sample' AND "driver_tracking_sessions"."driver_id"=NULLIF(current_setting('rove.tracking_driver',true),'')::uuid) WITH CHECK ("driver_tracking_sessions"."token_hash"=NULLIF(current_setting('rove.tracking_hash',true),'') AND current_setting('rove.tracking_mode',true)='sample' AND "driver_tracking_sessions"."driver_id"=NULLIF(current_setting('rove.tracking_driver',true),'')::uuid);--> statement-breakpoint
CREATE POLICY "tracking_revoke" ON "driver_tracking_sessions" AS PERMISSIVE FOR DELETE TO public USING ("driver_tracking_sessions"."driver_id"=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND current_setting('rove.actor_role',true)='driver'
  AND EXISTS(SELECT 1 FROM public.users u WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='driver' AND u.disabled=false) OR ("driver_tracking_sessions"."token_hash"=NULLIF(current_setting('rove.tracking_hash',true),'') AND current_setting('rove.tracking_mode',true)='revoke') OR current_setting('rove.actor_role', true) = 'staff'
  AND current_setting('rove.actor_mfa', true) = 'true'
  AND EXISTS (SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id
    WHERE u.id=NULLIF(current_setting('rove.actor_id', true), '')::uuid AND u.role='staff' AND u.disabled=false AND p.permission='privacy.close') AND "driver_tracking_sessions"."driver_id"=NULLIF(current_setting('rove.tracking_close_owner',true),'')::uuid AND EXISTS(SELECT 1 FROM public.users u WHERE u.id="driver_tracking_sessions"."driver_id" AND u.disabled=true));
--> statement-breakpoint
ALTER TABLE "driver_tracking_sessions" FORCE ROW LEVEL SECURITY;
