ALTER TABLE "ledger_journals" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "ledger_postings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "ledger_payment_read" ON "ledger_journals" AS PERMISSIVE FOR SELECT TO public USING ("ledger_journals"."attempt_id"=NULLIF(current_setting('rove.ledger_attempt',true),'')::uuid OR "ledger_journals"."created_transaction"=pg_current_xact_id()::text);--> statement-breakpoint
CREATE POLICY "ledger_capture_sweep" ON "ledger_journals" AS PERMISSIVE FOR SELECT TO public USING (current_setting('rove.capture_sweep',true)='true' AND "ledger_journals"."kind"='capture' AND EXISTS(SELECT 1 FROM public.payment_attempts p WHERE p.id="ledger_journals"."attempt_id" AND p.source=current_setting('rove.capture_source',true)));--> statement-breakpoint
CREATE POLICY "ledger_journal_append" ON "ledger_journals" AS PERMISSIVE FOR INSERT TO public WITH CHECK (jsonb_build_object('id',"ledger_journals"."id",'key',"ledger_journals"."key",'fingerprint',"ledger_journals"."fingerprint",'attempt',"ledger_journals"."attempt_id",'ride',"ledger_journals"."ride_id",'kind',"ledger_journals"."kind") = (NULLIF(current_setting('rove.ledger_append',true),'')::jsonb-'postings') AND "ledger_journals"."created_transaction"=pg_current_xact_id()::text);--> statement-breakpoint
CREATE POLICY "ledger_posting_read" ON "ledger_postings" AS PERMISSIVE FOR SELECT TO public USING (EXISTS(SELECT 1 FROM public.ledger_journals j WHERE j.id="ledger_postings"."journal_id" AND (j.attempt_id=NULLIF(current_setting('rove.ledger_attempt',true),'')::uuid OR j.created_transaction=pg_current_xact_id()::text)) OR "ledger_postings"."owner_id"=NULLIF(current_setting('rove.ledger_owner',true),'')::uuid);--> statement-breakpoint
CREATE POLICY "ledger_posting_append" ON "ledger_postings" AS PERMISSIVE FOR INSERT TO public WITH CHECK ("ledger_postings"."journal_id"=(NULLIF(current_setting('rove.ledger_append',true),'')::jsonb->>'id')::uuid AND (NULLIF(current_setting('rove.ledger_append',true),'')::jsonb->'postings') @> jsonb_build_array(jsonb_build_object('account',"ledger_postings"."account",'ownerId',"ledger_postings"."owner_id",'amountCents',"ledger_postings"."amount_cents")));
--> statement-breakpoint
ALTER TABLE ledger_journals FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE ledger_postings FORCE ROW LEVEL SECURITY;
