ALTER TABLE "offers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "offer_driver_read" ON "offers" AS PERMISSIVE FOR SELECT TO public USING ("offers"."driver_id"=NULLIF(current_setting('rove.actor_id',true),'')::uuid AND current_setting('rove.actor_role',true)='driver' AND EXISTS(SELECT 1 FROM public.users u WHERE u.id="offers"."driver_id" AND u.role='driver' AND u.disabled=false));--> statement-breakpoint
CREATE POLICY "offer_driver_update" ON "offers" AS PERMISSIVE FOR UPDATE TO public USING ("offers"."driver_id"=NULLIF(current_setting('rove.actor_id',true),'')::uuid AND current_setting('rove.actor_role',true)='driver' AND EXISTS(SELECT 1 FROM public.users u WHERE u.id="offers"."driver_id" AND u.role='driver' AND u.disabled=false)) WITH CHECK ("offers"."driver_id"=NULLIF(current_setting('rove.actor_id',true),'')::uuid AND current_setting('rove.actor_role',true)='driver' AND EXISTS(SELECT 1 FROM public.users u WHERE u.id="offers"."driver_id" AND u.role='driver' AND u.disabled=false) AND "offers"."status" IN ('accepted','declined'));--> statement-breakpoint
CREATE POLICY "offer_participant_read" ON "offers" AS PERMISSIVE FOR SELECT TO public USING ("offers"."status"='accepted' AND EXISTS(SELECT 1 FROM public.rides r JOIN public.users u ON u.id=r.rider_id WHERE r.id="offers"."ride_id" AND r.rider_id=NULLIF(current_setting('rove.actor_id',true),'')::uuid AND r.driver_id="offers"."driver_id" AND u.disabled=false AND current_setting('rove.actor_role',true)='rider'));--> statement-breakpoint
CREATE POLICY "offer_worker_read" ON "offers" AS PERMISSIVE FOR SELECT TO public USING ("offers"."ride_id"=NULLIF(current_setting('rove.offer_ride',true),'')::uuid OR (current_setting('rove.offer_matching',true)='true' AND "offers"."status"='pending') OR "offers"."id"=NULLIF(current_setting('rove.notification_offer',true),'')::uuid);--> statement-breakpoint
CREATE POLICY "offer_worker_update" ON "offers" AS PERMISSIVE FOR UPDATE TO public USING ("offers"."ride_id"=NULLIF(current_setting('rove.offer_ride',true),'')::uuid) WITH CHECK ("offers"."ride_id"=NULLIF(current_setting('rove.offer_ride',true),'')::uuid AND "offers"."status" IN ('expired','revoked'));--> statement-breakpoint
CREATE POLICY "offer_matching_insert" ON "offers" AS PERMISSIVE FOR INSERT TO public WITH CHECK ("offers"."ride_id"=NULLIF(current_setting('rove.offer_ride',true),'')::uuid AND current_setting('rove.offer_matching',true)='true' AND "offers"."status"='pending');--> statement-breakpoint
CREATE POLICY "offer_cleanup_read" ON "offers" AS PERMISSIVE FOR SELECT TO public USING (current_setting('rove.actor_role',true)='staff' AND current_setting('rove.actor_mfa',true)='true' AND EXISTS(SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id WHERE u.id=NULLIF(current_setting('rove.actor_id',true),'')::uuid AND u.disabled=false AND u.role='staff' AND p.permission='privacy.cleanup'));
--> statement-breakpoint
ALTER TABLE offers FORCE ROW LEVEL SECURITY;
