ALTER TABLE "drivers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "driver_scoped_read" ON "drivers" AS PERMISSIVE FOR SELECT TO public USING (("drivers"."id"=NULLIF(current_setting('rove.actor_id',true),'')::uuid OR "drivers"."id"=NULLIF(current_setting('rove.user_read',true),'')::uuid) OR (current_setting('rove.offer_matching',true)='true' AND NULLIF(current_setting('rove.offer_ride',true),'') IS NOT NULL) OR EXISTS(SELECT 1 FROM public.users u WHERE u.id="drivers"."id" AND u.subject=NULLIF(current_setting('rove.identity_subject',true),'')) OR EXISTS(SELECT 1 FROM public.rides r WHERE r.driver_id="drivers"."id" AND r.rider_id=NULLIF(current_setting('rove.actor_id',true),'')::uuid AND current_setting('rove.actor_role',true)='rider') OR EXISTS(SELECT 1 FROM public.offers o WHERE o.driver_id="drivers"."id" AND o.id=NULLIF(current_setting('rove.notification_offer',true),'')::uuid));--> statement-breakpoint
CREATE POLICY "driver_scoped_lock" ON "drivers" AS PERMISSIVE FOR UPDATE TO public USING ((("drivers"."id"=NULLIF(current_setting('rove.actor_id',true),'')::uuid OR "drivers"."id"=NULLIF(current_setting('rove.user_read',true),'')::uuid) OR (current_setting('rove.offer_matching',true)='true' AND NULLIF(current_setting('rove.offer_ride',true),'') IS NOT NULL) OR EXISTS(SELECT 1 FROM public.users u WHERE u.id="drivers"."id" AND u.subject=NULLIF(current_setting('rove.identity_subject',true),'')) OR EXISTS(SELECT 1 FROM public.rides r WHERE r.driver_id="drivers"."id" AND r.rider_id=NULLIF(current_setting('rove.actor_id',true),'')::uuid AND current_setting('rove.actor_role',true)='rider') OR EXISTS(SELECT 1 FROM public.offers o WHERE o.driver_id="drivers"."id" AND o.id=NULLIF(current_setting('rove.notification_offer',true),'')::uuid)) AND NULLIF(current_setting('rove.driver_write',true),'')::jsonb IS NULL) WITH CHECK (false);--> statement-breakpoint
CREATE POLICY "driver_signup" ON "drivers" AS PERMISSIVE FOR INSERT TO public WITH CHECK (EXISTS(SELECT 1 FROM public.users u WHERE u.id="drivers"."id" AND u.subject=NULLIF(current_setting('rove.identity_subject',true),'') AND u.role='driver' AND u.disabled=false) AND "drivers"."approved"=false AND "drivers"."online"=false AND "drivers"."payout_ready"=false AND "drivers"."payout_valid_until" IS NULL AND "drivers"."eligibility_expires_at" IS NULL AND "drivers"."vehicle" IS NULL AND "drivers"."location" IS NULL AND "drivers"."location_at" IS NULL AND "drivers"."location_sampled_at" IS NULL AND "drivers"."location_sequence"=0 AND "drivers"."service"='standard' AND "drivers"."coverage_radius_miles"=25);--> statement-breakpoint
CREATE POLICY "driver_scoped_mutation" ON "drivers" AS PERMISSIVE FOR UPDATE TO public USING (NULLIF(current_setting('rove.driver_write',true),'')::jsonb->>'kind' IN ('coverage','availability','location','eligibility','invalidate','vehicle','payout','closure') AND to_jsonb(drivers)=(NULLIF(current_setting('rove.driver_write',true),'')::jsonb->'before')) WITH CHECK (NULLIF(current_setting('rove.driver_write',true),'')::jsonb->>'kind' IN ('coverage','availability','location','eligibility','invalidate','vehicle','payout','closure') AND (to_jsonb(drivers)-(CASE NULLIF(current_setting('rove.driver_write',true),'')::jsonb->>'kind'
      WHEN 'coverage' THEN ARRAY['coverage_radius_miles']
      WHEN 'availability' THEN ARRAY['online','location','location_at','location_sampled_at','location_sequence']
      WHEN 'location' THEN ARRAY['location','location_at','location_sampled_at','location_sequence']
      WHEN 'eligibility' THEN ARRAY['approved','eligibility_expires_at']
      WHEN 'invalidate' THEN ARRAY['approved','eligibility_expires_at','location','location_at']
      WHEN 'vehicle' THEN ARRAY['vehicle','service','approved','eligibility_expires_at']
      WHEN 'payout' THEN ARRAY['payout_ready','payout_valid_until']
      WHEN 'closure' THEN ARRAY['online','location','location_at','location_sampled_at','location_sequence'] ELSE ARRAY[]::text[] END))=((NULLIF(current_setting('rove.driver_write',true),'')::jsonb->'before')-(CASE NULLIF(current_setting('rove.driver_write',true),'')::jsonb->>'kind'
      WHEN 'coverage' THEN ARRAY['coverage_radius_miles']
      WHEN 'availability' THEN ARRAY['online','location','location_at','location_sampled_at','location_sequence']
      WHEN 'location' THEN ARRAY['location','location_at','location_sampled_at','location_sequence']
      WHEN 'eligibility' THEN ARRAY['approved','eligibility_expires_at']
      WHEN 'invalidate' THEN ARRAY['approved','eligibility_expires_at','location','location_at']
      WHEN 'vehicle' THEN ARRAY['vehicle','service','approved','eligibility_expires_at']
      WHEN 'payout' THEN ARRAY['payout_ready','payout_valid_until']
      WHEN 'closure' THEN ARRAY['online','location','location_at','location_sampled_at','location_sequence'] ELSE ARRAY[]::text[] END)) AND (NULLIF(current_setting('rove.driver_write',true),'')::jsonb->>'kind'<>'invalidate' OR ("drivers"."approved"=false AND "drivers"."eligibility_expires_at" IS NULL)) AND (NULLIF(current_setting('rove.driver_write',true),'')::jsonb->>'kind'<>'closure' OR ("drivers"."online"=false AND "drivers"."location" IS NULL AND "drivers"."location_at" IS NULL AND "drivers"."location_sampled_at" IS NULL)));
--> statement-breakpoint
ALTER TABLE drivers FORCE ROW LEVEL SECURITY;
