CREATE TABLE "payment_review_cases" (
	"id" uuid PRIMARY KEY NOT NULL,
	"ride_id" uuid NOT NULL,
	"attempt_id" uuid NOT NULL,
	"source" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"acknowledged_at" timestamp with time zone,
	"acknowledged_by" uuid,
	"reference" text,
	CONSTRAINT "payment_review_ack_complete" CHECK (("payment_review_cases"."acknowledged_at" IS NULL AND "payment_review_cases"."acknowledged_by" IS NULL AND "payment_review_cases"."reference" IS NULL) OR ("payment_review_cases"."acknowledged_at" IS NOT NULL AND "payment_review_cases"."acknowledged_by" IS NOT NULL AND "payment_review_cases"."reference" IS NOT NULL AND "payment_review_cases"."reference" ~ '^[A-Za-z0-9][A-Za-z0-9._:/-]{2,119}$'))
);
--> statement-breakpoint
ALTER TABLE "payment_review_cases" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "payment_review_cases" ADD CONSTRAINT "payment_review_cases_ride_id_rides_id_fk" FOREIGN KEY ("ride_id") REFERENCES "public"."rides"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payment_review_cases" ADD CONSTRAINT "payment_review_cases_attempt_id_payment_attempts_id_fk" FOREIGN KEY ("attempt_id") REFERENCES "public"."payment_attempts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payment_review_cases" ADD CONSTRAINT "payment_review_cases_acknowledged_by_users_id_fk" FOREIGN KEY ("acknowledged_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "payment_review_queue" ON "payment_review_cases" USING btree ("acknowledged_at","id");--> statement-breakpoint
CREATE POLICY "payment_review_read" ON "payment_review_cases" AS PERMISSIVE FOR SELECT TO public USING ((current_setting('rove.actor_role',true)='staff' AND current_setting('rove.actor_mfa',true)='true' AND EXISTS(SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id WHERE u.id=NULLIF(current_setting('rove.actor_id',true),'')::uuid AND u.role='staff' AND u.disabled=false AND p.permission='payments.review')) OR "payment_review_cases"."id"=(NULLIF(current_setting('rove.payment_review_intake',true),'')::jsonb->>'id')::uuid);--> statement-breakpoint
CREATE POLICY "payment_review_intake" ON "payment_review_cases" AS PERMISSIVE FOR INSERT TO public WITH CHECK ("payment_review_cases"."id"=(NULLIF(current_setting('rove.payment_review_intake',true),'')::jsonb->>'id')::uuid AND "payment_review_cases"."ride_id"=(NULLIF(current_setting('rove.payment_review_intake',true),'')::jsonb->>'rideId')::uuid AND "payment_review_cases"."attempt_id"=(NULLIF(current_setting('rove.payment_review_intake',true),'')::jsonb->>'attemptId')::uuid AND "payment_review_cases"."source"=NULLIF(current_setting('rove.payment_review_intake',true),'')::jsonb->>'source' AND "payment_review_cases"."acknowledged_at" IS NULL AND "payment_review_cases"."acknowledged_by" IS NULL AND "payment_review_cases"."reference" IS NULL);--> statement-breakpoint
CREATE POLICY "payment_review_ack" ON "payment_review_cases" AS PERMISSIVE FOR UPDATE TO public USING ((current_setting('rove.actor_role',true)='staff' AND current_setting('rove.actor_mfa',true)='true' AND EXISTS(SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id WHERE u.id=NULLIF(current_setting('rove.actor_id',true),'')::uuid AND u.role='staff' AND u.disabled=false AND p.permission='payments.review')) AND "payment_review_cases"."id"=(NULLIF(current_setting('rove.payment_review_ack',true),'')::jsonb->>'id')::uuid AND "payment_review_cases"."acknowledged_at" IS NULL AND (to_jsonb(payment_review_cases)-'acknowledged_at'-'acknowledged_by'-'reference')=(NULLIF(current_setting('rove.payment_review_ack',true),'')::jsonb-'acknowledged_at'-'acknowledged_by'-'reference')) WITH CHECK ((current_setting('rove.actor_role',true)='staff' AND current_setting('rove.actor_mfa',true)='true' AND EXISTS(SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id WHERE u.id=NULLIF(current_setting('rove.actor_id',true),'')::uuid AND u.role='staff' AND u.disabled=false AND p.permission='payments.review')) AND to_jsonb(payment_review_cases)=NULLIF(current_setting('rove.payment_review_ack',true),'')::jsonb AND "payment_review_cases"."acknowledged_by"=NULLIF(current_setting('rove.actor_id',true),'')::uuid);--> statement-breakpoint
CREATE POLICY "payment_review_lock" ON "payment_review_cases" AS PERMISSIVE FOR UPDATE TO public USING (current_setting('rove.actor_role',true)='staff' AND current_setting('rove.actor_mfa',true)='true' AND EXISTS(SELECT 1 FROM public.users u JOIN public.staff_permissions p ON p.staff_id=u.id WHERE u.id=NULLIF(current_setting('rove.actor_id',true),'')::uuid AND u.role='staff' AND u.disabled=false AND p.permission='payments.review')) WITH CHECK (false);--> statement-breakpoint
ALTER TABLE payment_review_cases FORCE ROW LEVEL SECURITY;
