packages:
  - apps/*
  - packages/*
overrides:
  react-native-reanimated: 4.5.1
  react-native-worklets: 0.10.1
allowBuilds:
  '@embedded-postgres/darwin-arm64': true
  '@embedded-postgres/linux-x64': true
  esbuild: true
